[build-system]
requires = ["flit_core >=3.2,<4", "numpy", "scipy", "math", "cmath", "sys"]
build-backend = "flit_core.buildapi"

[project]
name = "hame"
authors = [{name = "Dominique Delande", email = "Dominique.Delande@lkb.upmc.fr"}]
dynamic = ["version", "description"]
